language: java
dist: trusty

addons:
    sonarcloud:
        organization: "softserve-social-projects"
        token:
            secure: "f3b8179f9f5659ebd4be99410d38f8770f7859c2"
            
jdk:
  - oraclejdk8

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=SoftServe-Social-Projects_GreenCity -DskipTests=true